In [ ]:
Numpy Array

In [4]:
import numpy as np

In [6]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [7]:
np.sqrt(10)

3.1622776601683795

In [8]:
print ('Minimum ',np.amin([25,30,57,18]))

print ('Maximum ',np.amax([25,30,57,18]))

Minimum  18
Maximum  57


In [9]:
#round off to next number

np.ceil(29.1)

30.0

In [10]:
np.ceil(np.sqrt(10))

4.0

In [11]:
np.ceil(np.sum(np.sqrt([5,10,15])))

10.0

In [ ]:
#Similarly there are many numpy functions 

In [12]:
np.array([5,9,13])

array([ 5,  9, 13])

In [13]:
xyz = np.array([5,9,13])

In [14]:
type(xyz)

numpy.ndarray

In [15]:
print (xyz)

[ 5  9 13]


In [16]:
#copy array into other
b=np.asarray(xyz)
print (b)

[ 5  9 13]


In [17]:
#dtype conversion
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
##data types

In [18]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

mat = np.array(my_mat)

print("Type\Class of the object:",type(mat))

print("Here is the matrix\n---------------\n",mat,"n\---------------")

print("Dimension of the matrix: ",mat.ndim)    #ndim gives the dimension, 2 for a matix , 1 for a vector

print("Sizes of the matrix: ",mat.size)     #size gives the total numbers of elements

print("Shape of this matrix: ",mat.shape)   #shape gives the number of elements along each axes

print("Data type of this matrix: ",mat.dtype)   # dtype gives the data type contained in the array

Type\Class of the object: <class 'numpy.ndarray'>
Here is the matrix
---------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] n\---------------
Dimension of the matrix:  2
Sizes of the matrix:  9
Shape of this matrix:  (3, 3)
Data type of this matrix:  int32


In [ ]:
#### arange & linspace

In [ ]:
### Donot work with python range

list(range(2,10.5,.4))           # This function is not working

In [25]:
a = np.arange(2,10.5,.4)

a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [26]:
# Reverse order

a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [28]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [29]:
print("linearly spaced numbers between 10 and 40\n--------------------------------------------------")

print(np.linspace(10,40,5))

linearly spaced numbers between 10 and 40
--------------------------------------------------
[10.  17.5 25.  32.5 40. ]


In [32]:
print("linearly spaced numbers between 10 and 40\n--------------------------------------------------")

print(np.linspace(10,40,5))

print("\n-------------------------------------------------------")

linearly spaced numbers between 10 and 40
--------------------------------------------------
[10.  17.5 25.  32.5 40. ]

-------------------------------------------------------


In [ ]:
# Include end point and check space between the points
# By default endpoint = True
# bydefault retstep = Flase

np.linspace(2.0,3.0, num=4, endpoint=Flase, retstep=True)

In [34]:
print(np.linspace(4.567867,25.98656,39, retstep=True))

(array([ 4.567867  ,  5.13151682,  5.69516663,  6.25881645,  6.82246626,
        7.38611608,  7.94976589,  8.51341571,  9.07706553,  9.64071534,
       10.20436516, 10.76801497, 11.33166479, 11.89531461, 12.45896442,
       13.02261424, 13.58626405, 14.14991387, 14.71356368, 15.2772135 ,
       15.84086332, 16.40451313, 16.96816295, 17.53181276, 18.09546258,
       18.65911239, 19.22276221, 19.78641203, 20.35006184, 20.91371166,
       21.47736147, 22.04101129, 22.60466111, 23.16831092, 23.73196074,
       24.29561055, 24.85926037, 25.42291018, 25.98656   ]), 0.5636498157894737)


In [ ]:
# MATRIX CREATION

In [35]:
print("Vector of zeroes\n---------------------")

print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [36]:
print("Matrix of zeroes\n---------------------")

print(np.zeros((5,6)))    # notice tuples

Matrix of zeroes
---------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [37]:
print("Matrix of ones\n---------------------")

print(np.ones((5,6)))    # Notice matrix dimension specified by tuples

Matrix of ones
---------------------
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [38]:
print("Matrix of 5's\n---------------------")

print(5*np.ones((4,3)))  

Matrix of 5's
---------------------
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [39]:
# Construct diagonal matrix

x = np.arange(30).reshape(6,5)

print (x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
# RANDOM NUMBER GENERATION

In [40]:
np.random.seed(6)       # Each seed number will generate similar data

print("Random number generation (from Uniform distribution)")

print(np.random.rand(10,6))

Random number generation (from Uniform distribution)
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [41]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")

print(np.random.randn(10,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.37550472  0.39636757 -0.47144628]
 [ 2.33660781  1.50278553 -0.59545972]
 [ 0.52834106  0.9398248   0.42628539]
 [-0.75815703 -0.16236698  0.72680996]
 [ 0.44408297 -0.85682264  0.44692842]
 [-1.01464799 -2.1323234   0.17386307]
 [ 0.95120126  0.44189739  1.46901739]
 [ 1.74951635  0.35353062 -0.64333729]
 [-0.04723705 -1.44903979 -0.03618977]
 [-0.09084699  0.17629034  1.09462041]]


In [42]:
print("Random integer vector:",np.random.randint(5,23,10))    # randint(low, high, # of samples to be drawn)

Random integer vector: [12 12 16 10  8 13 20 12  8 15]


In [43]:
print ("\nRandom integer matrix")

print(np.random.randint(1,3000,(6,7)))   # randint (low, high, # of samples to be drawn in a tuple to fo..)


Random integer matrix
[[1798 1082 1636  121 2401  792  600]
 [1440 2193 2596 2798  771 1295 1150]
 [1566  698 2945 1127 2660 2146 1625]
 [1994 1864  247 2705  105 1830  815]
 [2138 1209 2734  678  714  829 1666]
 [1133 2498 1395  538 1702  476  981]]


In [44]:
# one of the real time examples of randint is
while True:
    otp1 = np.random.randint(1000, 10000, 1)
    print('Your OTP is - ', otp1)
    user_otp = int(input('Enter OTP '))
    if otp1 ==user_otp:
        print('Login Success')
        break
    else:
        print("Invalid OTP, Generate new otp")
        continue
        

Your OTP is -  [7416]
Enter OTP 5214
Invalid OTP, Generate new otp
Your OTP is -  [9260]
Enter OTP 9260
Login Success


In [ ]:
## Sorting

In [45]:
from numpy.random import randint as ri

In [47]:
M = ri(1,100,25).reshape(5,5)  # Matrix of random interegrs

print("\n5x5 Matrix of random interegrs\n",'-'*50,"\n",M)

print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M))    #Default axis =1

print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0))


5x5 Matrix of random interegrs
 -------------------------------------------------- 
 [[99 55 96 67 13]
 [50 48 15 95 27]
 [65 92  3  3 86]
 [65 40 12 87 39]
 [43 17 10 22 30]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[13 55 67 96 99]
 [15 27 48 50 95]
 [ 3  3 65 86 92]
 [12 39 40 65 87]
 [10 17 22 30 43]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[43 17  3  3 13]
 [50 40 10 22 27]
 [65 48 12 67 30]
 [65 55 15 87 39]
 [99 92 96 95 86]]


In [48]:
print('Minimum = ',M.min(), 'and Maximum = ',M.max())

Minimum =  3 and Maximum =  99


In [ ]:
# Numpy Condition