In [2]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [3]:
np.sqrt(10)

3.1622776601683795

In [4]:
print ('Minimum ',np.amin([25,30,57,18]))

print ('Maximum ',np.amax([25,30,57,18]))

Minimum  18
Maximum  57


In [6]:
np.ceil(29.1)

30.0

In [8]:
np.ceil(np.sqrt(10))

4.0

In [9]:
np.ceil(np.sum(np.sqrt([5,10,15])))

10.0

In [ ]:
Similarly Many Function

In [4]:
np.array([5, 9, 13])

array([ 5,  9, 13])

In [5]:
xyz = np.array([5, 9, 13])

In [6]:
type(xyz)

numpy.ndarray

In [13]:
b=np.asarray(xyz)

print (b)

[ 5  9 13]


In [ ]:
how to copy

In [14]:
b=np.asarray(xyz)

print (b)

[ 5  9 13]


In [18]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [ ]:
data types

In [19]:
my_mat = [[1, 2 , 3],[4, 5, 6], [7, 8, 9]]

mat = np.array(my_mat)

print("Type/Class of this object: ",type(mat))

print("Here is the matrix\n-----------\n",mat,"\n-----------")

print("Dimension of this matrix: ",mat.ndim)

print("Size of this matrix: ",mat.size)

print("Shape of this matrix: ", mat.shape)

print("Data type of this matrix: ", mat.dtype)

Type/Class of this object:  <class 'numpy.ndarray'>
Here is the matrix
-----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------
Dimension of this matrix:  2
Size of this matrix:  9
Shape of this matrix:  (3, 3)
Data type of this matrix:  int32
